import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'

import React, { memo, useEffect, useRef, useState } from 'react'

import * as THREE from 'three'
import BIRDS from 'vanta/dist/vanta.cells.min.js'
const Home: NextPage = memo(() => {
  const wrapperRef = useRef(null)
  const [vantaEffect, setVantaEffect] = useState(0)
  useEffect(() => {
    if (!vantaEffect) {
      setVantaEffect(
        BIRDS({
          el: wrapperRef.current,
          THREE: THREE,
          mouseControls: true,
          touchControls: true,
          gyroControls: false,
          minHeight: 600.0,
          minWidth: 200.0,
          scale: 1.0,
          color2: 0x3535f2
        })
      )
    }
  }, [vantaEffect])
  return (
    <div>
      <Head>
        <title>unconstraint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={wrapperRef}>Foreground content goes here</div>
    </div>
  )
})
Home.displayName = 'Home'
export default Home
